<template>
  <div class="control-room">
    <div v-if="sidebarOpen" class="sidebar-scrim" @click="sidebarOpen = false"></div>
    <aside class="sidebar" :class="{ 'is-open': sidebarOpen }">
      <NativeButton class="brand" @click="navigate('overview')" aria-label="矿安智联首页"><span class="brand-mark"><AppIcon name="shield" /></span><span><strong>矿安智联<span class="brand-dot">.</span></strong><small>MINE SAFETY INTELLIGENCE</small></span></NativeButton>
      <div class="workspace-label"><span class="live-dot"></span>矿山安全工作台<span class="workspace-version">V2.0</span></div>
      <div class="nav-caption">工作空间 <span>WORKSPACE</span></div>
      <nav class="navigation" aria-label="主导航"><NativeButton v-for="page in navigation" :key="page.id" :class="['nav-item', { active: activePage === page.id }]" :aria-current="activePage === page.id ? 'page' : undefined" @click="navigate(page.id)"><AppIcon :name="page.icon" /><span>{{ page.label }}</span><span v-if="page.id === 'alarms' && pendingCount" class="nav-count">{{ pendingCount }}</span><AppIcon v-else-if="activePage === page.id" name="chevron" class="nav-chevron" /></NativeButton></nav>
      <div class="sidebar-bottom"><NativeButton class="assistant-shortcut" @click="navigate('ai')"><span class="assistant-symbol"><AppIcon name="spark" /></span><span><strong>矿安助手</strong><small>让安全数据更易理解</small></span><AppIcon name="arrow" /></NativeButton><div class="sidebar-network"><span :class="['live-dot', { offline: !isOnenetConnected }]"></span><span>{{ isOnenetConnected ? 'OneNET 云端已连接' : '正在连接数据服务' }}</span></div><div class="sidebar-signature"><span>多终端协同 · 智能安全研判</span><small>矿山人员与环境安全监测系统</small></div></div>
    </aside>
    <div class="main-shell">
      <header class="topbar"><div class="breadcrumbs"><NativeButton class="icon-button mobile-menu" @click="sidebarOpen = !sidebarOpen" aria-label="打开导航"><AppIcon name="menu" /></NativeButton><span>矿安智联</span><AppIcon name="chevron" /><strong>{{ currentPage.label }}</strong></div><div class="topbar-actions"><span class="topbar-date">{{ dateText }}<span>{{ clockText }}</span></span><NativeButton class="icon-button" @click="refreshTelemetry" :disabled="isFetchingOnenet" aria-label="刷新监测数据" title="刷新监测数据"><AppIcon name="refresh" :class="{ rotating: isFetchingOnenet }" /></NativeButton><NativeButton class="icon-button fullscreen-button" @click="toggleFullscreen" aria-label="全屏显示" title="全屏显示"><AppIcon name="expand" /></NativeButton><NativeButton class="notification-button icon-button" @click="navigate('alarms')" aria-label="查看报警"><AppIcon name="bell" /><i v-if="pendingCount"></i></NativeButton><span class="operator-avatar">安</span><span class="operator-label">安全工作台</span></div></header>
      <main class="page-content">
        <div class="page-heading"><div><div class="eyebrow"><span></span>{{ currentPage.english }}</div><h1>{{ currentPage.label }}<span v-if="activePage === 'overview'" class="heading-tag">CONTROL ROOM</span></h1><p>{{ activePage === 'overview' ? overviewSubtitle : currentPage.description }}</p></div><div class="heading-actions"><span v-if="activePage === 'overview'" :class="['status-pill', isOnenetConnected ? 'success' : 'warning']"><span class="status-dot"></span>{{ isOnenetConnected ? '云端连接正常' : '等待云端连接' }}</span><NativeButton v-if="activePage === 'employees'" class="primary-button" @click="editEmployee()"><AppIcon name="plus" />新增员工</NativeButton><NativeButton v-if="activePage === 'personnel'" class="secondary-button" @click="navigate('employees')"><AppIcon name="edit" />管理档案</NativeButton><NativeButton v-if="activePage === 'alarms'" class="secondary-button" @click="navigate('personnel')"><AppIcon name="users" />查看人员</NativeButton></div></div>
        <div v-if="isAlarm && activePage !== 'alarms'" class="alarm-strip"><AppIcon name="bell" /><span><strong>{{ boundEmployee?.name }} · 异常待核查</strong>{{ alarmMessage }}</span><NativeButton @click="navigate('alarms')">查看报警<AppIcon name="arrow" /></NativeButton></div>

        <template v-if="activePage === 'overview'">
          <section class="summary-grid" aria-label="安全概况">
            <div class="summary-card"><div class="summary-top"><span>人员档案</span><AppIcon name="users" /></div><div class="summary-number">{{ String(workers.length).padStart(2, '0') }}<small>人</small></div><div class="summary-foot"><span class="tiny-dot green"></span>已绑定 {{ workers.filter(w => w.device).length }} 人<span class="muted">全员档案</span></div></div>
            <div class="summary-card"><div class="summary-top"><span>数据可读设备</span><AppIcon name="pulse" /></div><div class="summary-number mint">{{ String(readableCount).padStart(2, '0') }}<small>套</small></div><div class="summary-foot"><span class="tiny-dot" :class="isOnenetConnected ? 'green' : 'amber'"></span>{{ isOnenetConnected ? (staleReadings ? '设备数据已过期' : '云端查询已接通') : '等待云端数据' }}<span class="muted">共 1 套</span></div></div>
            <div class="summary-card"><div class="summary-top"><span>待确认报警</span><AppIcon name="bell" /></div><div :class="['summary-number', pendingCount ? 'coral' : '']">{{ String(pendingCount).padStart(2, '0') }}<small>条</small></div><div class="summary-foot"><span class="tiny-dot" :class="pendingCount ? 'red' : 'green'"></span>{{ pendingCount ? '请及时核查异常事件' : '暂无待确认事件' }}<NativeButton @click="navigate('alarms')">查看<AppIcon name="chevron" /></NativeButton></div></div>
            <div class="summary-card risk-summary"><div class="summary-top"><span>当前监测状态</span><AppIcon name="shield" /></div><div :class="['summary-state', { coral: isAlarm }]">{{ riskLabel }}</div><div class="summary-foot"><span class="tiny-dot" :class="hasReadings && !isAlarm ? 'green' : 'amber'"></span>基于设备读数与本地阈值</div></div>
          </section>
          <div class="overview-main-grid mine-overview-grid">
            <section class="panel mine-distribution-panel"><div class="panel-heading"><div><h2><AppIcon name="pin" />井下人员分布图</h2><p>点击矿洞查看人员记录 · 点击头像查看监测详情</p></div><span class="subtle-badge">NFC 区域定位</span></div><MineMap :worker="boundEmployee" :area="area" :has-readings="hasReadings" :stale="staleReadings || !isOnenetConnected" :alarm="isAlarm" :connected="isOnenetConnected" @employee="openEmployee" @navigate="navigate" /></section>
            <section class="panel focus-personnel-panel"><div class="panel-heading"><h2><AppIcon name="users" />重点人员状态</h2><NativeButton class="text-button" @click="navigate('personnel')" aria-label="查看全部人员"><AppIcon name="arrow" /></NativeButton></div><div class="focus-personnel-list"><NativeButton v-for="worker in overviewWorkers" :key="worker.id" class="focus-worker" @click="openEmployee(worker)"><img :src="worker.avatar" :alt="worker.name + '的头像'"/><div class="focus-worker-info"><div class="focus-worker-name"><strong>{{ worker.name }}</strong><span :class="['status-pill', workerState(worker).tone]">{{ workerState(worker).label }}</span></div><dl><div><dt>工号</dt><dd>{{ worker.id }}</dd></div><div><dt>矿洞</dt><dd :class="{ blue: worker.device && hasReadings }">{{ workerLocation(worker) }}</dd></div><div><dt>岗位</dt><dd>{{ worker.role }}</dd></div><div class="focus-vitals"><dt>心率</dt><dd>{{ displayMetric(worker, heartRate) }}<small>bpm</small></dd><dt>血氧</dt><dd>{{ displayMetric(worker, bloodOxygen) }}<small>%</small></dd></div></dl></div></NativeButton></div><NativeButton class="focus-ai-link" @click="navigate('ai')"><span class="assistant-symbol"><AppIcon name="spark" /></span><span><strong>矿安助手 · AI 研判</strong><small>结合现场数据，辅助核查风险</small></span><AppIcon name="arrow"/></NativeButton></section>
          </div>
          <div class="overview-bottom-grid mine-bottom-grid"><section class="panel trend-panel"><div class="panel-heading"><div><h2><AppIcon name="heart" />心率趋势<small> bpm</small></h2><p>{{ boundEmployee.name }} · 最近采样</p></div><span class="chart-series-label"><i></i>{{ boundEmployee.name }}</span></div><MetricChart :rows="hasReadings ? historyRecords.heartRate.filter(row => Number(row.value) > 0) : []" unit="bpm" label="心率" color="#38cddd" chart-id="overview-heart" /></section><section class="panel trend-panel"><div class="panel-heading"><div><h2><AppIcon name="temp" />环境趋势</h2><p>{{ hasReadings ? areaText : '等待区域记录' }}</p></div><div class="segmented-control"><NativeButton :class="{ selected: environmentTrend === 'temp' }" @click="environmentTrend = 'temp'">温度</NativeButton><NativeButton :class="{ selected: environmentTrend === 'humi' }" @click="environmentTrend = 'humi'">湿度</NativeButton></div></div><MetricChart :rows="hasReadings ? historyRecords[environmentTrend] : []" :unit="environmentTrend === 'temp' ? '℃' : '%'" :label="environmentTrend === 'temp' ? '环境温度' : '环境湿度'" :color="environmentTrend === 'temp' ? '#42a9fa' : '#b392ef'" chart-id="overview-environment" /></section><section class="panel recent-alarm-panel"><div class="panel-heading"><div><h2><AppIcon name="bell" />最新报警信息</h2><p>实际设备异常事件</p></div><NativeButton class="text-button" @click="navigate('alarms')" aria-label="查看全部报警"><AppIcon name="arrow" /></NativeButton></div><div v-if="!recentAlarms.length" class="compact-empty"><span class="empty-icon"><AppIcon name="shield" /></span><strong>暂无报警记录</strong><p>收到异常数据后，事件将在这里显示</p></div><div v-else class="recent-alarms"><NativeButton v-for="event in recentAlarms" :key="event.id" @click="navigate('alarms')"><span :class="['event-mark', event.level]"><AppIcon name="bell" /></span><span><strong>{{ event.label }}</strong><small>{{ event.employeeName }} · {{ event.areaText || '区域未记录' }}<br/>{{ event.time.slice(11, 19) }}</small></span><span :class="['event-state', event.active ? 'coral' : 'mint']">{{ event.active ? '待核查' : '已恢复' }}</span></NativeButton></div></section></div>
        </template>

        <template v-if="activePage === 'personnel'">
          <div class="filter-bar"><label class="search-field"><AppIcon name="search" /><input v-model="searchText" placeholder="搜索姓名、工号或班组" aria-label="搜索人员" /></label><select v-model="teamFilter" aria-label="筛选班组"><option value="">全部班组</option><option v-for="team in teams" :key="team">{{ team }}</option></select><select v-model="statusFilter" aria-label="筛选设备绑定状态"><option value="">全部接入状态</option><option value="bound">已绑定设备</option><option value="unbound">未绑定设备</option></select><span class="filter-count">共 {{ filteredWorkers.length }} 名人员</span></div>
          <div class="personnel-layout"><section class="panel personnel-list"><div class="panel-heading"><h2>人员列表</h2><span class="subtle-badge">{{ filteredWorkers.length }} 人</span></div><NativeButton v-for="worker in filteredWorkers" :key="worker.id" :class="['personnel-row', { selected: selectedEmployeeId === worker.id }]" @click="selectedEmployeeId = worker.id"><img :src="worker.avatar" :alt="worker.name + '的头像'" /><span><strong>{{ worker.name }}</strong><small>{{ worker.id }} · {{ worker.team }}</small></span><span :class="['tiny-dot', workerState(worker).tone]"></span><AppIcon name="chevron" /></NativeButton><div v-if="!filteredWorkers.length" class="list-empty">没有找到匹配人员</div></section>
            <div class="personnel-detail"><section class="panel profile-panel"><div class="profile-identity"><img :src="selectedEmployee.avatar" :alt="selectedEmployee.name + '的头像'" /><div><div class="profile-name"><h2>{{ selectedEmployee.name }}</h2><span :class="['status-pill', workerState(selectedEmployee).tone]"><span class="status-dot"></span>{{ workerState(selectedEmployee).label }}</span></div><p>{{ selectedEmployee.role }}<span>·</span>{{ selectedEmployee.team }}</p><div class="profile-meta"><span>工号 <strong>{{ selectedEmployee.id }}</strong></span><span>设备 <strong>{{ selectedEmployee.device || '暂未绑定' }}</strong></span></div></div></div><NativeButton class="icon-button" @click="editEmployee(selectedEmployee)" aria-label="编辑当前员工"><AppIcon name="edit" /></NativeButton></section>
              <div v-if="!selectedEmployee.device" class="info-banner"><AppIcon name="info" /><span>这位员工暂未绑定设备。接入后，这里将显示其独立的监测数据。</span></div><div v-else-if="staleReadings || !isOnenetConnected" class="info-banner"><AppIcon name="clock" /><span>{{ staleReadings ? '设备数据已过期' : '云端正在连接' }}，以下显示最近一次收到的读数。</span></div>
              <div class="detail-metrics"><NativeButton v-for="metric in selectedMetrics" :key="metric.key" :class="['metric-card', { selected: selectedTrend === metric.key }]" @click="selectedTrend = metric.key"><div><span>{{ metric.label }}</span><AppIcon :name="metric.icon" :style="{ color: metric.color }" /></div><strong>{{ metricValue(metric, true) }}<small>{{ metric.unit }}</small></strong><span class="metric-note">{{ selectedHasReadings ? '最近设备读数' : '等待设备接入' }}<AppIcon name="chart" /></span></NativeButton></div>
              <section class="panel detail-trend"><div class="panel-heading"><div><h2>{{ trendMetric.label }}趋势</h2><p>{{ selectedEmployee.name }} · {{ trendMetric.unit }}</p></div><NativeButton class="text-button" :disabled="!selectedHasReadings" @click="openMetricHistory(selectedTrend)">历史明细<AppIcon name="arrow" /></NativeButton></div><MetricChart :rows="selectedTrendRows" :label="trendMetric.label" :unit="trendMetric.unit" :color="trendMetric.color" chart-id="personnel" /></section>
              <div class="detail-bottom-grid"><section class="panel personal-status"><div class="panel-heading"><h2>现场状态</h2><AppIcon name="helmet" /></div><dl><div><dt>最近所在区域</dt><dd>{{ workerLocation(selectedEmployee) }}</dd></div><div><dt>人员姿态</dt><dd :class="{ coral: selectedHasReadings && String(sstatus) === '1' }">{{ selectedHasReadings && sstatus !== '' ? (String(sstatus) === '1' ? '跌倒 / 姿态异常' : '未检测到跌倒') : '暂无数据' }}</dd></div><div><dt>手环读数</dt><dd>{{ selectedHasReadings ? (isBraceletWorn ? '已收到生命体征读数' : '暂无有效生命体征读数') : '暂无数据' }}</dd></div><div><dt>主动求助</dt><dd :class="{ coral: selectedHasReadings && String(help) === '1' }">{{ selectedHasReadings && help !== '' ? (String(help) === '1' ? '已收到求助信号' : '暂无求助信号') : '暂无数据' }}</dd></div></dl><NativeButton class="evacuation-button" :disabled="!selectedEmployee.device || isSending" @click="showEvacuationModal"><AppIcon name="exit" />发送撤离指令</NativeButton></section><section class="panel location-timeline"><div class="panel-heading"><h2>最近区域与状态记录</h2><AppIcon name="clock" /></div><div v-if="!selectedHasReadings || !recentEvents.length" class="compact-empty"><AppIcon name="pin" /><p>暂无人员活动记录</p></div><div v-else class="timeline"><div v-for="(event, index) in recentEvents" :key="index"><span class="timeline-dot"></span><strong>{{ event.text }}</strong><small>{{ event.time }}</small></div></div></section></div>
            </div>
          </div>
        </template>

        <template v-if="activePage === 'employees'">
          <div class="management-banner"><span class="management-banner-icon"><AppIcon name="folder" /></span><div><strong>让每一份监测数据，对应清晰的人员身份。</strong><p>编辑姓名、班组与照片。当前档案保存在本浏览器，P4 档案同步尚未接入。</p></div><span class="subtle-badge">本地档案</span></div>
          <section class="panel employee-table-panel"><div class="table-toolbar"><label class="search-field"><AppIcon name="search" /><input v-model="searchText" placeholder="搜索员工姓名、工号或班组" aria-label="搜索员工档案" /></label><span>{{ workers.length }} 份人员档案</span><NativeButton class="secondary-button" @click="exportEmployees"><AppIcon name="download" />导出档案</NativeButton></div><div class="table-scroll"><table class="employee-table"><thead><tr><th>员工信息</th><th>岗位 / 班组</th><th>设备绑定</th><th>档案状态</th><th>操作</th></tr></thead><tbody><tr v-for="worker in filteredWorkers" :key="worker.id"><td><div class="table-person"><img :src="worker.avatar" :alt="worker.name + '的头像'" /><span><strong>{{ worker.name }}</strong><small>{{ worker.id }}</small></span></div></td><td><div class="table-stack"><strong>{{ worker.role }}</strong><small>{{ worker.team }}</small></div></td><td><span v-if="worker.device" class="device-binding"><AppIcon name="link" />{{ worker.device }}</span><span v-else class="muted">未绑定设备</span></td><td><span class="status-pill muted"><span class="status-dot"></span>本浏览器已保存</span></td><td><div class="table-actions"><NativeButton @click="editEmployee(worker)"><AppIcon name="edit" />编辑</NativeButton><NativeButton @click="openEmployee(worker)" aria-label="查看员工监测详情"><AppIcon name="arrow" /></NativeButton></div></td></tr></tbody></table><div v-if="!filteredWorkers.length" class="table-empty">没有找到匹配的员工档案</div></div><div class="table-footer"><span>默认姓名与 AI 头像用于演示，可替换为实际员工资料。</span><span>共 {{ filteredWorkers.length }} 条</span></div></section>
          <div class="management-help-grid"><div class="panel help-card"><AppIcon name="user" /><h3>姓名与工号独立管理</h3><p>工号保持固定。修改姓名、照片或班组后，人员身份仍然清晰。</p></div><div class="panel help-card"><AppIcon name="upload" /><h3>真实照片或 AI 头像</h3><p>支持上传员工照片，也可选择与 P4 屏幕一致的默认工业人物头像。</p></div><div class="panel help-card"><AppIcon name="device" /><h3>为终端同步做好准备</h3><p>本版完成网页档案管理。设备接入和 P4 自动同步将在后续联调中实现。</p></div></div>
        </template>

        <template v-if="activePage === 'alarms'">
          <div class="alarm-summary-grid"><div class="panel alarm-stat"><span class="event-mark danger"><AppIcon name="bell" /></span><div><strong>{{ activeAlarmSpecs.length }}</strong><span>当前异常指标</span></div></div><div class="panel alarm-stat"><span class="event-mark warning"><AppIcon name="clock" /></span><div><strong>{{ pendingCount }}</strong><span>待确认事件</span></div></div><div class="panel alarm-stat"><span class="event-mark success"><AppIcon name="check" /></span><div><strong>{{ alarmEvents.filter(e => !e.active).length }}</strong><span>已恢复事件</span></div></div></div>
          <section class="panel alarm-table-panel"><div class="panel-heading"><div><h2>报警事件</h2><p>基于实际设备读数，记录本浏览器观察到的异常与恢复</p></div><div class="segmented-control"><NativeButton :class="{ selected: alarmFilter === 'all' }" @click="alarmFilter = 'all'">全部</NativeButton><NativeButton :class="{ selected: alarmFilter === 'pending' }" @click="alarmFilter = 'pending'">待确认</NativeButton><NativeButton :class="{ selected: alarmFilter === 'recovered' }" @click="alarmFilter = 'recovered'">已恢复</NativeButton></div></div><div v-if="!filteredAlarms.length" class="large-empty"><span class="empty-illustration"><AppIcon name="shield" /></span><h3>{{ alarmFilter === 'pending' ? '暂无待确认报警' : '暂无报警事件' }}</h3><p>设备出现异常读数时，事件会自动记录在这里。</p><span class="subtle-badge">实际设备事件</span></div><div v-else class="table-scroll"><table class="alarm-table"><thead><tr><th>异常事件</th><th>人员</th><th>发生时间</th><th>监测状态</th><th>处理</th></tr></thead><tbody><tr v-for="event in filteredAlarms" :key="event.id"><td><div class="alarm-name"><span :class="['event-mark', event.level]"><AppIcon name="bell" /></span><span><strong>{{ event.label }}</strong><small>{{ event.detail }}</small></span></div></td><td>{{ event.employeeName }}<small class="table-id">{{ event.employeeId }}</small></td><td class="mono">{{ event.time }}</td><td><span :class="['status-pill', event.active ? 'danger' : 'success']">{{ event.active ? '异常待核查' : '指标已恢复' }}</span></td><td><NativeButton v-if="!event.acknowledged" class="text-button" @click="acknowledgeAlarm(event)"><AppIcon name="check" />确认已知晓</NativeButton><span v-else class="muted">已确认</span></td></tr></tbody></table></div></section><div class="info-banner"><AppIcon name="info" /><span>确认表示已知晓事件，不会清除设备异常。气体数据按原始读数展示，沿用现有项目阈值。</span></div>
        </template>

        <template v-if="activePage === 'ai'">
          <div class="ai-page-grid"><section class="panel ai-analysis-panel"><div class="ai-analysis-intro"><span class="ai-logo large"><AppIcon name="spark" /></span><div class="eyebrow">YOUR SAFETY COPILOT</div><h2>矿安助手</h2><p>结合现场数据与历史记录，<br />辅助理解风险，核查异常原因。</p></div><div class="analysis-person"><img :src="boundEmployee.avatar" :alt="boundEmployee.name + '的头像'" /><span><small>当前数据对象</small><strong>{{ boundEmployee.name }}<span>{{ boundEmployee.id }}</span></strong></span><span :class="['tiny-dot', workerState(boundEmployee).tone]"></span></div><div class="analysis-source-list"><div><AppIcon name="pulse" /><span>设备读数</span><strong>{{ hasReadings ? (staleReadings ? '数据已过期' : '已采集') : '等待数据' }}</strong></div><div><AppIcon name="pin" /><span>区域记录</span><strong>{{ historyRecords.area.length }} 条</strong></div><div><AppIcon name="chart" /><span>人员状态</span><strong>{{ historyRecords.sstatus.length }} 条</strong></div></div><NativeButton class="primary-button analyze-button" :disabled="isAiAnalyzing || !hasReadings || !isOnenetConnected || staleReadings" @click="analyzeCurrentEmployee"><AppIcon name="spark" />{{ isAiAnalyzing ? '正在研判…' : '开始安全研判' }}</NativeButton><div v-if="aiDecision" class="analysis-result"><div><span>研判结果</span><span :class="['status-pill', aiDecision.riskLevel === 'danger' ? 'danger' : aiDecision.riskLevel === 'watch' ? 'warning' : 'success']">{{ aiRiskText }}</span></div><h3>{{ aiDecision.summary }}</h3><p>{{ aiDecision.reason }}</p><dl><div><dt>趋势判断</dt><dd>{{ aiDecision.trend || '暂无趋势结论' }}</dd></div><div><dt>处置建议</dt><dd>{{ aiDecision.suggestion || '请结合现场情况核查' }}</dd></div></dl><small>{{ aiDecision.source === 'xiaomi' ? '小米 MiMo 云端研判' : '本地阈值参考 / 云端结果不可用' }}</small></div><div class="ai-disclaimer"><AppIcon name="info" /><span>AI 结论用于辅助核查，处置以现场实际情况为依据。</span></div></section>
            <section class="panel ai-chat-panel"><div class="panel-heading"><div><h2><AppIcon name="spark" />安全研判对话</h2><p>小米 MiMo · 基于已采集的设备数据</p></div><NativeButton class="text-button" :disabled="isAiChatting || !aiChatMessages.length" @click="clearAiChat">清空对话</NativeButton></div><scroll-view class="chat-messages" scroll-y :scroll-top="aiChatScrollTop"><div v-if="!aiChatMessages.length" class="chat-welcome"><div class="chat-welcome-logo"><AppIcon name="spark" /></div><h3>你好，我是矿安助手。</h3><p>你可以询问人员经过的区域、异常发生时间，<br />或让我们一起检查最近的监测数据。</p><div class="quick-question-grid"><NativeButton v-for="question in aiQuickQuestions" :key="question" :disabled="!hasReadings || !isOnenetConnected || staleReadings" @click="askAiQuickQuestion(question)">{{ question }}<AppIcon name="arrow" /></NativeButton></div></div><div v-for="(message, index) in aiChatMessages" :key="index" :class="['chat-message', message.role]"><span class="chat-avatar"><AppIcon :name="message.role === 'user' ? 'user' : 'spark'" /></span><div><div class="chat-message-meta"><strong>{{ message.role === 'user' ? '我' : '矿安助手' }}</strong><time>{{ message.time }}</time></div><div class="chat-bubble">{{ message.content }}</div></div></div></scroll-view><form class="chat-composer" @submit.prevent="askAiQuestion"><textarea v-model="aiQuestion" :disabled="isAiChatting || !hasReadings || !isOnenetConnected || staleReadings" :placeholder="hasReadings ? '询问现场状态、异常原因或历史记录…' : '设备接入后，即可开始安全研判对话'" aria-label="发送给矿安助手的问题" @keydown.enter.exact.prevent="askAiQuestion"></textarea><NativeButton type="submit" @click="askAiQuestion" :disabled="isAiChatting || !aiQuestion.trim() || !hasReadings || !isOnenetConnected || staleReadings" aria-label="发送问题"><AppIcon name="send" /></NativeButton></form><div class="chat-footnote">Enter 发送 · Shift + Enter 换行<span>当前仅分析已绑定设备人员的数据</span></div></section></div>
        </template>

        <template v-if="activePage === 'devices'">
          <section class="panel connectivity-panel"><div class="panel-heading"><div><h2>多终端协同链路</h2><p>人员终端与基站协作，网页提供集中监测和智能研判</p></div><span class="subtle-badge">系统架构</span></div><div class="device-flow"><div><span class="device-flow-icon"><AppIcon name="watch" /></span><strong>智能手环</strong><small>生命体征采集</small></div><span class="flow-link">蓝牙<AppIcon name="arrow" /></span><div><span class="device-flow-icon"><AppIcon name="helmet" /></span><strong>智能头盔</strong><small>环境与人员状态</small></div><span class="flow-link">现场无线链路<AppIcon name="arrow" /></span><div><span class="device-flow-icon"><AppIcon name="device" /></span><strong>P4 基站</strong><small>数据汇聚与本地显示</small></div><span class="flow-link">OneNET<AppIcon name="arrow" /></span><div><span class="device-flow-icon accent"><AppIcon name="spark" /></span><strong>网页与 AI</strong><small>监测 · 管理 · 研判</small></div></div></section>
          <div class="device-card-grid"><section class="panel gateway-card"><div class="panel-heading"><span class="device-flow-icon"><AppIcon name="device" /></span><span :class="['status-pill', isOnenetConnected ? 'success' : 'warning']">{{ isOnenetConnected ? '云端可访问' : '连接中' }}</span></div><h2>P4 矿安基站</h2><p>现场数据汇聚与人员监测终端</p><dl><div><dt>云端设备名称</dt><dd>ESP32S3</dd></div><div><dt>当前绑定人员</dt><dd>{{ boundEmployee.name }}</dd></div><div><dt>最后查询时间</dt><dd class="mono">{{ updateTime || '等待数据' }}</dd></div><div><dt>档案同步</dt><dd class="amber">尚未接入</dd></div></dl></section><section class="panel gateway-card"><div class="panel-heading"><span class="device-flow-icon"><AppIcon name="helmet" /></span><span class="status-pill muted">设备 01</span></div><h2>头盔与手环采集端</h2><p>当前网页使用一套真实设备数据</p><dl><div><dt>环境数据</dt><dd>温度 / 湿度 / MQ2 / MQ7</dd></div><div><dt>人员数据</dt><dd>心率 / 血氧 / 跌倒 / 求助</dd></div><div><dt>位置来源</dt><dd>NFC 区域记录</dd></div><div><dt>数据状态</dt><dd>{{ workerState(boundEmployee).label }}</dd></div></dl></section></div><div class="info-banner"><AppIcon name="info" /><span>云端可访问表示查询服务已接通。手环、头盔与基站各自的在线状态，需要终端心跳与回执接入后确认。</span></div>
        </template>
        <footer class="page-footer"><span><span class="tiny-dot" :class="isOnenetConnected ? 'green' : 'amber'"></span>{{ updateTime ? '最后读取 ' + updateTime : '正在等待设备数据' }}</span><span>矿安智联<span class="footer-separator">/</span>多终端协同安全监测与 AI 研判</span></footer>
      </main>
    </div>
    <div v-if="employeeEditorOpen && employeeDraft" class="modal-backdrop" @click.self="closeEmployeeEditor" @keydown.esc="closeEmployeeEditor"><section class="modal employee-editor" role="dialog" aria-modal="true" aria-labelledby="employee-editor-title"><div class="modal-header"><div><div class="eyebrow">EMPLOYEE PROFILE</div><h2 id="employee-editor-title">{{ workers.some(w => w.id === employeeDraft.id) ? '编辑员工档案' : '新增员工' }}</h2></div><NativeButton class="icon-button" @click="closeEmployeeEditor" aria-label="关闭员工编辑"><AppIcon name="close" /></NativeButton></div><form @submit.prevent="saveEmployee"><div class="editor-photo-row"><img :src="employeeDraft.avatar" alt="员工头像预览" /><div><strong>员工头像</strong><p>JPG / PNG / WebP，最大 5 MB</p><label class="secondary-button upload-button" for="employee-photo"><AppIcon name="upload" />{{ photoLoading ? '处理照片中…' : '上传照片' }}<PhotoInput id="employee-photo" class="file-input" type="file" accept="image/jpeg,image/png,image/webp" :disabled="photoLoading" @change="uploadPortrait" /></label></div></div><div class="avatar-picker"><span>或选择默认 AI 头像</span><div><NativeButton v-for="avatar in avatars" :key="avatar" type="button" :class="{ selected: employeeDraft.avatar === avatar }" @click="employeeDraft.avatar = avatar" :aria-label="'选择默认头像 ' + (avatars.indexOf(avatar) + 1)"><img :src="avatar" alt="默认工业员工头像" /><span v-if="employeeDraft.avatar === avatar"><AppIcon name="check" /></span></NativeButton></div></div><div class="form-grid"><label>员工姓名 <span>*</span><input v-model="employeeDraft.name" maxlength="16" placeholder="请输入员工姓名" required /></label><label>员工工号<input :value="employeeDraft.id" disabled /></label><label>所属班组 <span>*</span><input v-model="employeeDraft.team" maxlength="24" placeholder="例如：采掘一班" required /></label><label>岗位名称<input v-model="employeeDraft.role" maxlength="24" placeholder="例如：安全巡检员" /></label></div><div class="editor-device"><AppIcon name="link" /><span>绑定设备</span><strong>{{ employeeDraft.device || '暂未绑定' }}</strong></div><p class="form-hint">档案保存在本浏览器。P4 自动同步与更多设备绑定将在后续接入。</p><div v-if="editorError" class="form-error" role="alert">{{ editorError }}</div><div class="modal-footer"><NativeButton type="button" class="secondary-button" @click="closeEmployeeEditor">取消</NativeButton><NativeButton class="primary-button" type="submit" :disabled="photoLoading" @click="saveEmployee"><AppIcon name="check" />保存档案</NativeButton></div></form></section></div>
    <div v-if="historyModalVisible" class="modal-backdrop" @click.self="closeHistory"><section class="modal history-modal" role="dialog" aria-modal="true" aria-labelledby="history-title"><div class="modal-header"><div><div class="eyebrow">TELEMETRY HISTORY</div><h2 id="history-title">{{ activeHistoryConfig.name }}历史记录</h2></div><NativeButton class="icon-button" @click="closeHistory" aria-label="关闭历史记录"><AppIcon name="close" /></NativeButton></div><div class="history-summary"><span>最高 <strong>{{ historyMax }} {{ activeHistoryConfig.unit }}</strong></span><span>最低 <strong>{{ historyMin }} {{ activeHistoryConfig.unit }}</strong></span><span>共 <strong>{{ activeHistoryRows.length }} 条记录</strong></span></div><MetricChart :rows="historyRecords[activeHistoryKey]" :label="activeHistoryConfig.name" :unit="activeHistoryConfig.unit" chart-id="history" /><div class="history-table-scroll"><table><thead><tr><th>记录时间</th><th>{{ activeHistoryConfig.name }}</th></tr></thead><tbody><tr v-for="(row, index) in activeHistoryRows.slice(0, 200)" :key="index"><td>{{ row.time }}</td><td>{{ row.text }} {{ activeHistoryConfig.unit }}</td></tr></tbody></table><div v-if="!activeHistoryRows.length" class="table-empty">暂无历史数据</div></div><p class="form-hint">最近 200 条明细 · 当前浏览器采集记录</p></section></div>
    <div v-if="showModal" class="modal-backdrop" @click.self="cancelEvacuation"><section class="modal evacuation-modal" role="dialog" aria-modal="true" aria-labelledby="evacuation-title"><span class="evacuation-symbol"><AppIcon name="exit" /></span><h2 id="evacuation-title">确认发送撤离指令？</h2><p>指令将提交至 <strong>{{ boundEmployee.name }}</strong> 绑定的设备 01。请先核实现场情况与指令对象。</p><div class="info-banner"><AppIcon name="info" /><span>云平台接收指令后，仍需现场终端执行。</span></div><div class="modal-footer"><NativeButton class="secondary-button" @click="cancelEvacuation">取消</NativeButton><NativeButton class="danger-button" @click="confirmEvacuation" :disabled="isSending">确认发送</NativeButton></div></section></div>
    <div v-if="toastMessage" class="toast" role="status"><AppIcon name="check" />{{ toastMessage }}</div>
  </div>
</template>
<script>
import telemetry from '../../lib/telemetry.js';
import controlRoom from '../../lib/control-room.js';
import AppIcon from '../../components/AppIcon.vue';
import MetricChart from '../../components/MetricChart.vue';
import PhotoInput from '../../components/PhotoInput.vue';
import NativeButton from '../../components/NativeButton.vue';
import MineMap from '../../components/MineMap.vue';
export default { mixins: [telemetry, controlRoom], components: { AppIcon, MetricChart, PhotoInput, NativeButton, MineMap } };
</script>
